[package]
name = "petersburg"
version = "0.0.1"

[dependencies]
itertools = "*"
png = "0.17.5"
rand = "*"
gtk = "*"
gdk = "*"
glib = "*"
colored = "*"
once_cell = "*"
single_value_channel = "*"
crossbeam = "*"
priority-queue = "*"
cairo-rs = {version = "0.15.10", features = ["png"]}
